version: "2"

services:
  mariadb:
    image: docker.io/bitnami/mariadb:10.6
    environment:
      # ALLOW_EMPTY_PASSWORD is recommended only for development.
      - ALLOW_EMPTY_PASSWORD=yes
      - MARIADB_USER=root
      - MARIADB_DATABASE=video
    volumes:
      - "mariadb_data:/bitnami/mariadb"
    healthcheck:
      test: ["CMD", "/opt/bitnami/scripts/mariadb/healthcheck.sh"]
      interval: 15s
      timeout: 5s
      retries: 6
  phpmyadmin:
    image: docker.io/bitnami/phpmyadmin:5
    ports:
      - "8080:8080"
      - "8443:8443"
    depends_on:
      - mariadb
  composer:
    image: composer:2.5.4
    command: ["composer", "install"]
    volumes:
      - "./video-app:/app"
  myapp:
    image: docker.io/bitnami/laravel:9
    ports:
      - "3000:3000"
      - "8000:8000"
    environment:
      - DB_HOST=mariadb
      - DB_PORT=3306
      - DB_USERNAME=root
      - DB_DATABASE=video
    volumes:
      - "./video-app:/app"
    depends_on:
      - mariadb
      - phpmyadmin
volumes:
  mariadb_data:
    driver: local
